### ISSUE TITLE
Handle log rollover fail due to windows lock

### ISSUE THREAD

**Issue by jontwo** [jontwo/backpy#9]
Implement a rolling log handler that can deal with Windows being a pain.

```
Logged from file file_index.py, line 114
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
```

**Comment by jontwo** [comment]
Fixed in https://github.com/jontwo/backpy/commit/f6e90f4c7760d6299c642cce08bcd4ce1e503d52
